import sys
import re

if __name__ == '__main__':
    print('start cannon_glue.py')
    
    f=open('./cannon_glue.cpp','r')
    alllines=f.readlines()
    f.close()
    f=open('./cannon_glue.cpp','w+')
    for eachline in alllines:
        a=re.sub('new World\(','World::create(',eachline)
        a=re.sub('new Body\(','Body::create(',a)
        a=re.sub('new Box\(','Box::create(',a)
        a=re.sub('new Sphere\(','Sphere::create(',a)
        a=re.sub('new Plane\(','Plane::create(',a)
        a=re.sub('new Particle\(','Particle::create(',a)
        a=re.sub('new ConvexPolyhedron\(','ConvexPolyhedron::create(',a)
        a=re.sub('new Cylinder\(','Cylinder::create(',a)
        a=re.sub('new Trimesh\(','Trimesh::create(',a)
        a=re.sub('new Heightfield\(','Heightfield::create(',a)
        a=re.sub('new Material\(','Material::create(',a)
        a=re.sub('new ContactMaterial\(','ContactMaterial::create(',a)
        a=re.sub('new DistanceConstraint\(','DistanceConstraint::create(',a)
        a=re.sub('new PointToPointConstraint\(','PointToPointConstraint::create(',a)
        a=re.sub('new LockConstraint\(','LockConstraint::create(',a)
        a=re.sub('new HingeConstraint\(','HingeConstraint::create(',a)
        a=re.sub('new ConeTwistConstraint\(','ConeTwistConstraint::create(',a)
        a=re.sub('new Spring\(','Spring::create(',a)
        a=re.sub('new RigidVehicle\(','RigidVehicle::create(',a)
        a=re.sub('new RaycastVehicle\(','RaycastVehicle::create(',a)
        a=re.sub('new NaiveBroadphase\(','NaiveBroadphase::create(',a)
        a=re.sub('new GridBroadphase\(','GridBroadphase::create(',a)
        a=re.sub('new SAPBroadphase\(','SAPBroadphase::create(',a)
        a=re.sub('new GSSolver\(','GSSolver::create(',a)
        a=re.sub('new SplitSolver\(','SplitSolver::create(',a)
        a=re.sub('new EventTarget\(','EventTarget::create(',a)
        a=re.sub('new Ray\(','Ray::create(',a)
        a=re.sub('new RaycastResult\(','RaycastResult::create(',a)
        a=re.sub('new SPHSystem\(','SPHSystem::create(',a)
        f.writelines(a)
    f.close()

    print('end cannon_glue.py')
